---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-skylanas-com
  namespace: default
spec:
  secretName: local-skylanas-com-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.local.skylanas.com"
  dnsNames:
  - "local.skylanas.com"
  - "*.local.skylanas.com"
